apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-versions
  namespace: {{ .Release.Namespace }}
data:
  platformVersion: "{{ .Values.platformVersion }}"
  buildVersion: "{{ .Values.buildVersion }}"
  intelEmail: "{{ .Values.intelEmail }}"
